# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /mlnStudy

spring:
  application:
    name: web-sales-backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ""
            client-secret: ""
            redirect-uri: ""
            scope:
              - email
              - profile
              
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mln_study}?sslMode=${MYSQL_SSL_MODE:DISABLED}&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:root}}
    password: ${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:}}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  signerKey: ""
  expiration: 
  refreshable-duration: 
  temp-expiration: 