name: Deploy Backend + Frontend

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend
          push: true
          tags: hieupnh12/mln-backend:1.0

      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./Frontend
          push: true
          tags: hieupnh12/mln-frontend:test-build
          build-args: |
            VITE_API_BASE_URL=https://hocllct.io.vn/api
            VITE_API_WITH_CREDENTIALS=false

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/mln-deploy
            sudo docker compose --env-file .env.production pull
            sudo docker compose --env-file .env.production up -d --force-recreate
            sudo docker image prune -f
